//SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.20;
interface LotteryStruct {
    
    /// @dev RoundInfo is used as a parameter in lottery.sol.
    /// @param winningNumber The winning number generated by Chainlink's VRF.
    /// @param totalPrizeAmount The sum of total sales and the first-place prize sourced from the team fund.
    /// @param onlyFirstPlacePrizeAmountFromTeam The first-place prize sourced from the team fund.
    /// @param firstPlacePrizeAmountFromFees 10% of the total sale (70%) distributed to the lottery.
    /// @param totalFirstPlacePrizeAmount The sum of onlyFirstPlacePrizeAmountFromTeam and firstPlacePrizeAmountFromFees.
    /// @param secondPlacePrizeAmountFromFees 60% of the total sale (70%) distributed to the lottery.
    /// @param thirdPlacePrizeAmountFromFees 20% of the total sale (70%) distributed to the lottery.
    /// @param totalFirstPlaceWinners The number of first-place winners.
    /// @param totalSecondPlaceWinners The number of second-place winners.
    /// @param totalThirdPlaceWinners The number of third-place winners.
    /// @param totalSoldTickets The number of sold tickets.
    /// @param totalSales The total sales.
    /// @param announcedBlock The block number to announce winners.
    
    struct RoundInfo {
        string winningNumber;
        uint256 totalPrizeAmount;
        uint256 onlyFirstPlacePrizeAmountFromTeam;
        uint256 firstPlacePrizeAmountFromFees;
        uint256 totalFirstPlacePrizeAmount;
        uint256 secondPlacePrizeAmountFromFees;
        uint256 thirdPlacePrizeAmountFromFees;
        uint256 totalFirstPlaceWinners;
        uint256 totalSecondPlaceWinners;
        uint256 totalThirdPlaceWinners;
        uint256 totalSoldTickets;
        uint256 totalSales;
        uint256 announcedBlock;
    }

}